/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LayoutIndexRouteImport } from './routes/_layout.index'
import { Route as LayoutSettingsRouteImport } from './routes/_layout.settings'
import { Route as LayoutTasksTaskIdRouteImport } from './routes/_layout.tasks.$taskId'
import { Route as ApiTasksTaskIdChatRouteImport } from './routes/api/tasks/$taskId/chat'

const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSettingsRoute = LayoutSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutTasksTaskIdRoute = LayoutTasksTaskIdRouteImport.update({
  id: '/tasks/$taskId',
  path: '/tasks/$taskId',
  getParentRoute: () => LayoutRoute,
} as any)
const ApiTasksTaskIdChatRoute = ApiTasksTaskIdChatRouteImport.update({
  id: '/api/tasks/$taskId/chat',
  path: '/api/tasks/$taskId/chat',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof LayoutIndexRoute
  '/settings': typeof LayoutSettingsRoute
  '/tasks/$taskId': typeof LayoutTasksTaskIdRoute
  '/api/tasks/$taskId/chat': typeof ApiTasksTaskIdChatRoute
}
export interface FileRoutesByTo {
  '/settings': typeof LayoutSettingsRoute
  '/': typeof LayoutIndexRoute
  '/tasks/$taskId': typeof LayoutTasksTaskIdRoute
  '/api/tasks/$taskId/chat': typeof ApiTasksTaskIdChatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/_layout/settings': typeof LayoutSettingsRoute
  '/_layout/': typeof LayoutIndexRoute
  '/_layout/tasks/$taskId': typeof LayoutTasksTaskIdRoute
  '/api/tasks/$taskId/chat': typeof ApiTasksTaskIdChatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/settings' | '/tasks/$taskId' | '/api/tasks/$taskId/chat'
  fileRoutesByTo: FileRoutesByTo
  to: '/settings' | '/' | '/tasks/$taskId' | '/api/tasks/$taskId/chat'
  id:
    | '__root__'
    | '/_layout'
    | '/_layout/settings'
    | '/_layout/'
    | '/_layout/tasks/$taskId'
    | '/api/tasks/$taskId/chat'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
  ApiTasksTaskIdChatRoute: typeof ApiTasksTaskIdChatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/settings': {
      id: '/_layout/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof LayoutSettingsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/tasks/$taskId': {
      id: '/_layout/tasks/$taskId'
      path: '/tasks/$taskId'
      fullPath: '/tasks/$taskId'
      preLoaderRoute: typeof LayoutTasksTaskIdRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/api/tasks/$taskId/chat': {
      id: '/api/tasks/$taskId/chat'
      path: '/api/tasks/$taskId/chat'
      fullPath: '/api/tasks/$taskId/chat'
      preLoaderRoute: typeof ApiTasksTaskIdChatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface LayoutRouteChildren {
  LayoutSettingsRoute: typeof LayoutSettingsRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
  LayoutTasksTaskIdRoute: typeof LayoutTasksTaskIdRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutSettingsRoute: LayoutSettingsRoute,
  LayoutIndexRoute: LayoutIndexRoute,
  LayoutTasksTaskIdRoute: LayoutTasksTaskIdRoute,
}

const LayoutRouteWithChildren = LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
  ApiTasksTaskIdChatRoute: ApiTasksTaskIdChatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
