/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WebhookRouteImport } from './routes/webhook'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LayoutIndexRouteImport } from './routes/_layout.index'
import { Route as LayoutSettingsRouteImport } from './routes/_layout.settings'
import { Route as LayoutRunnerIndexRouteImport } from './routes/_layout.runner.index'
import { Route as ApiTasksShapeRouteImport } from './routes/api/tasks/shape'
import { Route as ApiPullRequestsShapeRouteImport } from './routes/api/pull-requests/shape'
import { Route as ApiProviderCredentialsShapeRouteImport } from './routes/api/provider-credentials/shape'
import { Route as ApiProjectsShapeRouteImport } from './routes/api/projects/shape'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as LayoutTasksTaskIdRouteImport } from './routes/_layout.tasks.$taskId'
import { Route as LayoutRunnerSessionIdRouteImport } from './routes/_layout.runner.$sessionId'
import { Route as ApiTasksMessagesShapeRouteImport } from './routes/api/tasks/messages/shape'
import { Route as ApiTasksTaskIdStreamRouteImport } from './routes/api/tasks/$taskId/stream'
import { Route as ApiInternalTaskRunsExecutionIdMessageRouteImport } from './routes/api/internal/task-runs/$executionId/message'
import { Route as ApiInternalTaskRunsExecutionIdHeartbeatRouteImport } from './routes/api/internal/task-runs/$executionId/heartbeat'
import { Route as ApiInternalTaskRunsExecutionIdFailRouteImport } from './routes/api/internal/task-runs/$executionId/fail'
import { Route as ApiInternalTaskRunsExecutionIdCompleteRouteImport } from './routes/api/internal/task-runs/$executionId/complete'
import { Route as ApiInternalTaskRunsExecutionIdBranchRouteImport } from './routes/api/internal/task-runs/$executionId/branch'

const WebhookRoute = WebhookRouteImport.update({
  id: '/webhook',
  path: '/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSettingsRoute = LayoutSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutRunnerIndexRoute = LayoutRunnerIndexRouteImport.update({
  id: '/runner/',
  path: '/runner/',
  getParentRoute: () => LayoutRoute,
} as any)
const ApiTasksShapeRoute = ApiTasksShapeRouteImport.update({
  id: '/api/tasks/shape',
  path: '/api/tasks/shape',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPullRequestsShapeRoute = ApiPullRequestsShapeRouteImport.update({
  id: '/api/pull-requests/shape',
  path: '/api/pull-requests/shape',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProviderCredentialsShapeRoute =
  ApiProviderCredentialsShapeRouteImport.update({
    id: '/api/provider-credentials/shape',
    path: '/api/provider-credentials/shape',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiProjectsShapeRoute = ApiProjectsShapeRouteImport.update({
  id: '/api/projects/shape',
  path: '/api/projects/shape',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutTasksTaskIdRoute = LayoutTasksTaskIdRouteImport.update({
  id: '/tasks/$taskId',
  path: '/tasks/$taskId',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutRunnerSessionIdRoute = LayoutRunnerSessionIdRouteImport.update({
  id: '/runner/$sessionId',
  path: '/runner/$sessionId',
  getParentRoute: () => LayoutRoute,
} as any)
const ApiTasksMessagesShapeRoute = ApiTasksMessagesShapeRouteImport.update({
  id: '/api/tasks/messages/shape',
  path: '/api/tasks/messages/shape',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTasksTaskIdStreamRoute = ApiTasksTaskIdStreamRouteImport.update({
  id: '/api/tasks/$taskId/stream',
  path: '/api/tasks/$taskId/stream',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiInternalTaskRunsExecutionIdMessageRoute =
  ApiInternalTaskRunsExecutionIdMessageRouteImport.update({
    id: '/api/internal/task-runs/$executionId/message',
    path: '/api/internal/task-runs/$executionId/message',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiInternalTaskRunsExecutionIdHeartbeatRoute =
  ApiInternalTaskRunsExecutionIdHeartbeatRouteImport.update({
    id: '/api/internal/task-runs/$executionId/heartbeat',
    path: '/api/internal/task-runs/$executionId/heartbeat',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiInternalTaskRunsExecutionIdFailRoute =
  ApiInternalTaskRunsExecutionIdFailRouteImport.update({
    id: '/api/internal/task-runs/$executionId/fail',
    path: '/api/internal/task-runs/$executionId/fail',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiInternalTaskRunsExecutionIdCompleteRoute =
  ApiInternalTaskRunsExecutionIdCompleteRouteImport.update({
    id: '/api/internal/task-runs/$executionId/complete',
    path: '/api/internal/task-runs/$executionId/complete',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiInternalTaskRunsExecutionIdBranchRoute =
  ApiInternalTaskRunsExecutionIdBranchRouteImport.update({
    id: '/api/internal/task-runs/$executionId/branch',
    path: '/api/internal/task-runs/$executionId/branch',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof LayoutIndexRoute
  '/login': typeof LoginRoute
  '/webhook': typeof WebhookRoute
  '/settings': typeof LayoutSettingsRoute
  '/runner/$sessionId': typeof LayoutRunnerSessionIdRoute
  '/tasks/$taskId': typeof LayoutTasksTaskIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/projects/shape': typeof ApiProjectsShapeRoute
  '/api/provider-credentials/shape': typeof ApiProviderCredentialsShapeRoute
  '/api/pull-requests/shape': typeof ApiPullRequestsShapeRoute
  '/api/tasks/shape': typeof ApiTasksShapeRoute
  '/runner/': typeof LayoutRunnerIndexRoute
  '/api/tasks/$taskId/stream': typeof ApiTasksTaskIdStreamRoute
  '/api/tasks/messages/shape': typeof ApiTasksMessagesShapeRoute
  '/api/internal/task-runs/$executionId/branch': typeof ApiInternalTaskRunsExecutionIdBranchRoute
  '/api/internal/task-runs/$executionId/complete': typeof ApiInternalTaskRunsExecutionIdCompleteRoute
  '/api/internal/task-runs/$executionId/fail': typeof ApiInternalTaskRunsExecutionIdFailRoute
  '/api/internal/task-runs/$executionId/heartbeat': typeof ApiInternalTaskRunsExecutionIdHeartbeatRoute
  '/api/internal/task-runs/$executionId/message': typeof ApiInternalTaskRunsExecutionIdMessageRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/webhook': typeof WebhookRoute
  '/settings': typeof LayoutSettingsRoute
  '/': typeof LayoutIndexRoute
  '/runner/$sessionId': typeof LayoutRunnerSessionIdRoute
  '/tasks/$taskId': typeof LayoutTasksTaskIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/projects/shape': typeof ApiProjectsShapeRoute
  '/api/provider-credentials/shape': typeof ApiProviderCredentialsShapeRoute
  '/api/pull-requests/shape': typeof ApiPullRequestsShapeRoute
  '/api/tasks/shape': typeof ApiTasksShapeRoute
  '/runner': typeof LayoutRunnerIndexRoute
  '/api/tasks/$taskId/stream': typeof ApiTasksTaskIdStreamRoute
  '/api/tasks/messages/shape': typeof ApiTasksMessagesShapeRoute
  '/api/internal/task-runs/$executionId/branch': typeof ApiInternalTaskRunsExecutionIdBranchRoute
  '/api/internal/task-runs/$executionId/complete': typeof ApiInternalTaskRunsExecutionIdCompleteRoute
  '/api/internal/task-runs/$executionId/fail': typeof ApiInternalTaskRunsExecutionIdFailRoute
  '/api/internal/task-runs/$executionId/heartbeat': typeof ApiInternalTaskRunsExecutionIdHeartbeatRoute
  '/api/internal/task-runs/$executionId/message': typeof ApiInternalTaskRunsExecutionIdMessageRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/login': typeof LoginRoute
  '/webhook': typeof WebhookRoute
  '/_layout/settings': typeof LayoutSettingsRoute
  '/_layout/': typeof LayoutIndexRoute
  '/_layout/runner/$sessionId': typeof LayoutRunnerSessionIdRoute
  '/_layout/tasks/$taskId': typeof LayoutTasksTaskIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/projects/shape': typeof ApiProjectsShapeRoute
  '/api/provider-credentials/shape': typeof ApiProviderCredentialsShapeRoute
  '/api/pull-requests/shape': typeof ApiPullRequestsShapeRoute
  '/api/tasks/shape': typeof ApiTasksShapeRoute
  '/_layout/runner/': typeof LayoutRunnerIndexRoute
  '/api/tasks/$taskId/stream': typeof ApiTasksTaskIdStreamRoute
  '/api/tasks/messages/shape': typeof ApiTasksMessagesShapeRoute
  '/api/internal/task-runs/$executionId/branch': typeof ApiInternalTaskRunsExecutionIdBranchRoute
  '/api/internal/task-runs/$executionId/complete': typeof ApiInternalTaskRunsExecutionIdCompleteRoute
  '/api/internal/task-runs/$executionId/fail': typeof ApiInternalTaskRunsExecutionIdFailRoute
  '/api/internal/task-runs/$executionId/heartbeat': typeof ApiInternalTaskRunsExecutionIdHeartbeatRoute
  '/api/internal/task-runs/$executionId/message': typeof ApiInternalTaskRunsExecutionIdMessageRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/webhook'
    | '/settings'
    | '/runner/$sessionId'
    | '/tasks/$taskId'
    | '/api/auth/$'
    | '/api/projects/shape'
    | '/api/provider-credentials/shape'
    | '/api/pull-requests/shape'
    | '/api/tasks/shape'
    | '/runner/'
    | '/api/tasks/$taskId/stream'
    | '/api/tasks/messages/shape'
    | '/api/internal/task-runs/$executionId/branch'
    | '/api/internal/task-runs/$executionId/complete'
    | '/api/internal/task-runs/$executionId/fail'
    | '/api/internal/task-runs/$executionId/heartbeat'
    | '/api/internal/task-runs/$executionId/message'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/webhook'
    | '/settings'
    | '/'
    | '/runner/$sessionId'
    | '/tasks/$taskId'
    | '/api/auth/$'
    | '/api/projects/shape'
    | '/api/provider-credentials/shape'
    | '/api/pull-requests/shape'
    | '/api/tasks/shape'
    | '/runner'
    | '/api/tasks/$taskId/stream'
    | '/api/tasks/messages/shape'
    | '/api/internal/task-runs/$executionId/branch'
    | '/api/internal/task-runs/$executionId/complete'
    | '/api/internal/task-runs/$executionId/fail'
    | '/api/internal/task-runs/$executionId/heartbeat'
    | '/api/internal/task-runs/$executionId/message'
  id:
    | '__root__'
    | '/_layout'
    | '/login'
    | '/webhook'
    | '/_layout/settings'
    | '/_layout/'
    | '/_layout/runner/$sessionId'
    | '/_layout/tasks/$taskId'
    | '/api/auth/$'
    | '/api/projects/shape'
    | '/api/provider-credentials/shape'
    | '/api/pull-requests/shape'
    | '/api/tasks/shape'
    | '/_layout/runner/'
    | '/api/tasks/$taskId/stream'
    | '/api/tasks/messages/shape'
    | '/api/internal/task-runs/$executionId/branch'
    | '/api/internal/task-runs/$executionId/complete'
    | '/api/internal/task-runs/$executionId/fail'
    | '/api/internal/task-runs/$executionId/heartbeat'
    | '/api/internal/task-runs/$executionId/message'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
  LoginRoute: typeof LoginRoute
  WebhookRoute: typeof WebhookRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiProjectsShapeRoute: typeof ApiProjectsShapeRoute
  ApiProviderCredentialsShapeRoute: typeof ApiProviderCredentialsShapeRoute
  ApiPullRequestsShapeRoute: typeof ApiPullRequestsShapeRoute
  ApiTasksShapeRoute: typeof ApiTasksShapeRoute
  ApiTasksTaskIdStreamRoute: typeof ApiTasksTaskIdStreamRoute
  ApiTasksMessagesShapeRoute: typeof ApiTasksMessagesShapeRoute
  ApiInternalTaskRunsExecutionIdBranchRoute: typeof ApiInternalTaskRunsExecutionIdBranchRoute
  ApiInternalTaskRunsExecutionIdCompleteRoute: typeof ApiInternalTaskRunsExecutionIdCompleteRoute
  ApiInternalTaskRunsExecutionIdFailRoute: typeof ApiInternalTaskRunsExecutionIdFailRoute
  ApiInternalTaskRunsExecutionIdHeartbeatRoute: typeof ApiInternalTaskRunsExecutionIdHeartbeatRoute
  ApiInternalTaskRunsExecutionIdMessageRoute: typeof ApiInternalTaskRunsExecutionIdMessageRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/webhook': {
      id: '/webhook'
      path: '/webhook'
      fullPath: '/webhook'
      preLoaderRoute: typeof WebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/settings': {
      id: '/_layout/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof LayoutSettingsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/runner/': {
      id: '/_layout/runner/'
      path: '/runner'
      fullPath: '/runner/'
      preLoaderRoute: typeof LayoutRunnerIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/api/tasks/shape': {
      id: '/api/tasks/shape'
      path: '/api/tasks/shape'
      fullPath: '/api/tasks/shape'
      preLoaderRoute: typeof ApiTasksShapeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/pull-requests/shape': {
      id: '/api/pull-requests/shape'
      path: '/api/pull-requests/shape'
      fullPath: '/api/pull-requests/shape'
      preLoaderRoute: typeof ApiPullRequestsShapeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/provider-credentials/shape': {
      id: '/api/provider-credentials/shape'
      path: '/api/provider-credentials/shape'
      fullPath: '/api/provider-credentials/shape'
      preLoaderRoute: typeof ApiProviderCredentialsShapeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/projects/shape': {
      id: '/api/projects/shape'
      path: '/api/projects/shape'
      fullPath: '/api/projects/shape'
      preLoaderRoute: typeof ApiProjectsShapeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/tasks/$taskId': {
      id: '/_layout/tasks/$taskId'
      path: '/tasks/$taskId'
      fullPath: '/tasks/$taskId'
      preLoaderRoute: typeof LayoutTasksTaskIdRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/runner/$sessionId': {
      id: '/_layout/runner/$sessionId'
      path: '/runner/$sessionId'
      fullPath: '/runner/$sessionId'
      preLoaderRoute: typeof LayoutRunnerSessionIdRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/api/tasks/messages/shape': {
      id: '/api/tasks/messages/shape'
      path: '/api/tasks/messages/shape'
      fullPath: '/api/tasks/messages/shape'
      preLoaderRoute: typeof ApiTasksMessagesShapeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tasks/$taskId/stream': {
      id: '/api/tasks/$taskId/stream'
      path: '/api/tasks/$taskId/stream'
      fullPath: '/api/tasks/$taskId/stream'
      preLoaderRoute: typeof ApiTasksTaskIdStreamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/internal/task-runs/$executionId/message': {
      id: '/api/internal/task-runs/$executionId/message'
      path: '/api/internal/task-runs/$executionId/message'
      fullPath: '/api/internal/task-runs/$executionId/message'
      preLoaderRoute: typeof ApiInternalTaskRunsExecutionIdMessageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/internal/task-runs/$executionId/heartbeat': {
      id: '/api/internal/task-runs/$executionId/heartbeat'
      path: '/api/internal/task-runs/$executionId/heartbeat'
      fullPath: '/api/internal/task-runs/$executionId/heartbeat'
      preLoaderRoute: typeof ApiInternalTaskRunsExecutionIdHeartbeatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/internal/task-runs/$executionId/fail': {
      id: '/api/internal/task-runs/$executionId/fail'
      path: '/api/internal/task-runs/$executionId/fail'
      fullPath: '/api/internal/task-runs/$executionId/fail'
      preLoaderRoute: typeof ApiInternalTaskRunsExecutionIdFailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/internal/task-runs/$executionId/complete': {
      id: '/api/internal/task-runs/$executionId/complete'
      path: '/api/internal/task-runs/$executionId/complete'
      fullPath: '/api/internal/task-runs/$executionId/complete'
      preLoaderRoute: typeof ApiInternalTaskRunsExecutionIdCompleteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/internal/task-runs/$executionId/branch': {
      id: '/api/internal/task-runs/$executionId/branch'
      path: '/api/internal/task-runs/$executionId/branch'
      fullPath: '/api/internal/task-runs/$executionId/branch'
      preLoaderRoute: typeof ApiInternalTaskRunsExecutionIdBranchRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface LayoutRouteChildren {
  LayoutSettingsRoute: typeof LayoutSettingsRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
  LayoutRunnerSessionIdRoute: typeof LayoutRunnerSessionIdRoute
  LayoutTasksTaskIdRoute: typeof LayoutTasksTaskIdRoute
  LayoutRunnerIndexRoute: typeof LayoutRunnerIndexRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutSettingsRoute: LayoutSettingsRoute,
  LayoutIndexRoute: LayoutIndexRoute,
  LayoutRunnerSessionIdRoute: LayoutRunnerSessionIdRoute,
  LayoutTasksTaskIdRoute: LayoutTasksTaskIdRoute,
  LayoutRunnerIndexRoute: LayoutRunnerIndexRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
  LoginRoute: LoginRoute,
  WebhookRoute: WebhookRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiProjectsShapeRoute: ApiProjectsShapeRoute,
  ApiProviderCredentialsShapeRoute: ApiProviderCredentialsShapeRoute,
  ApiPullRequestsShapeRoute: ApiPullRequestsShapeRoute,
  ApiTasksShapeRoute: ApiTasksShapeRoute,
  ApiTasksTaskIdStreamRoute: ApiTasksTaskIdStreamRoute,
  ApiTasksMessagesShapeRoute: ApiTasksMessagesShapeRoute,
  ApiInternalTaskRunsExecutionIdBranchRoute:
    ApiInternalTaskRunsExecutionIdBranchRoute,
  ApiInternalTaskRunsExecutionIdCompleteRoute:
    ApiInternalTaskRunsExecutionIdCompleteRoute,
  ApiInternalTaskRunsExecutionIdFailRoute:
    ApiInternalTaskRunsExecutionIdFailRoute,
  ApiInternalTaskRunsExecutionIdHeartbeatRoute:
    ApiInternalTaskRunsExecutionIdHeartbeatRoute,
  ApiInternalTaskRunsExecutionIdMessageRoute:
    ApiInternalTaskRunsExecutionIdMessageRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
